name: LimitlessTrialVaults
version: '1.0-SNAPSHOT'
author: 'Pgini'
description: 'Removes the one time use limit on trial vaults'
main: net.divinitystudios.limitlesstrialvaults.Main
api-version: '1.21'